"""etapa 2: persona, vacante, postulacion, notificacion_vacante, evento_comercial

Revision ID: 382e7662c70f
Revises: f1a2b3c4d5e6
Create Date: 2026-07-24 14:06:15.411864
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '382e7662c70f'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic autogenerate no detecta cambios en los VALORES de un enum nativo de Postgres
    # (solo columnas/tablas) — se agrega a mano. Seguro dentro de una transacción desde PG 12+,
    # siempre que el valor nuevo no se USE en la misma transacción (acá solo se agrega).
    op.execute("ALTER TYPE estado_empresa ADD VALUE IF NOT EXISTS 'pendiente_verificacion'")
    op.execute("ALTER TYPE estado_empresa ADD VALUE IF NOT EXISTS 'rechazada'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('puesto_deseado', sa.String(length=160), nullable=True),
    sa.Column('fecha_nacimiento', sa.String(length=20), nullable=True),
    sa.Column('identificacion', sa.String(length=40), nullable=True),
    sa.Column('provincia', sa.String(length=120), nullable=True),
    sa.Column('codigo_postal_ciudad', sa.String(length=120), nullable=True),
    sa.Column('perfil_profesional', sa.String(length=160), nullable=True),
    sa.Column('formacion', sa.Text(), nullable=True),
    sa.Column('descripcion_perfil', sa.Text(), nullable=True),
    sa.Column('disp_viajar', sa.Boolean(), nullable=False),
    sa.Column('disp_cambio_residencia', sa.Boolean(), nullable=False),
    sa.Column('idiomas', sa.JSON(), nullable=True),
    sa.Column('primer_empleo', sa.Boolean(), nullable=False),
    sa.Column('experiencias', sa.JSON(), nullable=True),
    sa.Column('cv_nombre', sa.String(length=255), nullable=True),
    sa.Column('cv_url', sa.Text(), nullable=True),
    sa.Column('firma_consentimiento_url', sa.Text(), nullable=True),
    sa.Column('firma_conformidad_url', sa.Text(), nullable=True),
    sa.Column('reset_token', sa.String(length=64), nullable=True),
    sa.Column('reset_expira', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_email'), 'persona', ['email'], unique=True)
    op.create_table('vacante',
    sa.Column('puesto', sa.String(length=160), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('provincia', sa.String(length=120), nullable=True),
    sa.Column('localidad', sa.String(length=120), nullable=True),
    sa.Column('modalidad', sa.String(length=40), nullable=True),
    sa.Column('jornada', sa.String(length=40), nullable=True),
    sa.Column('vacantes', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=80), nullable=True),
    sa.Column('zona', sa.String(length=120), nullable=True),
    sa.Column('responsabilidades', sa.Text(), nullable=True),
    sa.Column('requisitos_excluyentes', sa.Text(), nullable=True),
    sa.Column('requisitos_deseables', sa.Text(), nullable=True),
    sa.Column('habilidades', sa.Text(), nullable=True),
    sa.Column('idioma_requerido', sa.String(length=60), nullable=True),
    sa.Column('nivel_idioma', sa.String(length=40), nullable=True),
    sa.Column('salario_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salario_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ocultar_salario', sa.Boolean(), nullable=False),
    sa.Column('horario', sa.String(length=160), nullable=True),
    sa.Column('beneficios', sa.Text(), nullable=True),
    sa.Column('beneficios_otros', sa.Text(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reclutador', sa.String(length=160), nullable=True),
    sa.Column('pregunta_1', sa.Text(), nullable=True),
    sa.Column('pregunta_2', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacante_tenant_id'), 'vacante', ['tenant_id'], unique=False)
    op.create_table('evento_comercial',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=60), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('canal', sa.String(length=40), nullable=True),
    sa.Column('destinatarios', sa.Text(), nullable=True),
    sa.Column('estado_notificacion', sa.String(length=20), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evento_comercial_tenant_id'), 'evento_comercial', ['tenant_id'], unique=False)
    op.create_table('notificacion_vacante',
    sa.Column('vacante_id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('puntaje', sa.Integer(), nullable=False),
    sa.Column('motivos', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacante_id'], ['vacante.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacion_vacante_persona_id'), 'notificacion_vacante', ['persona_id'], unique=False)
    op.create_index(op.f('ix_notificacion_vacante_tenant_id'), 'notificacion_vacante', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notificacion_vacante_vacante_id'), 'notificacion_vacante', ['vacante_id'], unique=False)
    op.create_table('postulacion',
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('vacante_id', sa.Uuid(), nullable=False),
    sa.Column('respuestas_busqueda', sa.JSON(), nullable=True),
    sa.Column('firma_consentimiento_url', sa.Text(), nullable=True),
    sa.Column('fecha_firma_consentimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firma_conformidad_url', sa.Text(), nullable=True),
    sa.Column('fecha_firma_conformidad', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacante_id'], ['vacante.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'vacante_id', name='uq_postulacion_persona_vacante')
    )
    op.create_index(op.f('ix_postulacion_persona_id'), 'postulacion', ['persona_id'], unique=False)
    op.create_index(op.f('ix_postulacion_tenant_id'), 'postulacion', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_postulacion_vacante_id'), 'postulacion', ['vacante_id'], unique=False)
    op.add_column('empresa', sa.Column('cuit', sa.String(length=20), nullable=True))
    op.add_column('empresa', sa.Column('rubro', sa.String(length=120), nullable=True))
    op.add_column('empresa', sa.Column('dni', sa.String(length=20), nullable=True))
    op.add_column('empresa', sa.Column('selfie_url', sa.Text(), nullable=True))
    op.add_column('empresa', sa.Column('dni_frente_url', sa.Text(), nullable=True))
    op.add_column('empresa', sa.Column('dni_dorso_url', sa.Text(), nullable=True))
    op.add_column('empresa', sa.Column('firma_legal_url', sa.Text(), nullable=True))
    op.add_column('empresa', sa.Column('nombre_verificado', sa.String(length=255), nullable=True))
    op.add_column(
        'empresa',
        sa.Column('acepto_terminos', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('empresa', sa.Column('fecha_acepto_terminos', sa.DateTime(timezone=True), nullable=True))
    op.add_column('evaluado', sa.Column('persona_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_evaluado_persona_id'), 'evaluado', ['persona_id'], unique=False)
    op.create_foreign_key(None, 'evaluado', 'persona', ['persona_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Nota: Postgres no soporta ALTER TYPE ... DROP VALUE — los valores 'pendiente_verificacion'
    # y 'rechazada' agregados al enum estado_empresa quedan (no rompen nada por quedarse).
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evaluado', type_='foreignkey')
    op.drop_index(op.f('ix_evaluado_persona_id'), table_name='evaluado')
    op.drop_column('evaluado', 'persona_id')
    op.drop_column('empresa', 'fecha_acepto_terminos')
    op.drop_column('empresa', 'acepto_terminos')
    op.drop_column('empresa', 'nombre_verificado')
    op.drop_column('empresa', 'firma_legal_url')
    op.drop_column('empresa', 'dni_dorso_url')
    op.drop_column('empresa', 'dni_frente_url')
    op.drop_column('empresa', 'selfie_url')
    op.drop_column('empresa', 'dni')
    op.drop_column('empresa', 'rubro')
    op.drop_column('empresa', 'cuit')
    op.drop_index(op.f('ix_postulacion_vacante_id'), table_name='postulacion')
    op.drop_index(op.f('ix_postulacion_tenant_id'), table_name='postulacion')
    op.drop_index(op.f('ix_postulacion_persona_id'), table_name='postulacion')
    op.drop_table('postulacion')
    op.drop_index(op.f('ix_notificacion_vacante_vacante_id'), table_name='notificacion_vacante')
    op.drop_index(op.f('ix_notificacion_vacante_tenant_id'), table_name='notificacion_vacante')
    op.drop_index(op.f('ix_notificacion_vacante_persona_id'), table_name='notificacion_vacante')
    op.drop_table('notificacion_vacante')
    op.drop_index(op.f('ix_evento_comercial_tenant_id'), table_name='evento_comercial')
    op.drop_table('evento_comercial')
    op.drop_index(op.f('ix_vacante_tenant_id'), table_name='vacante')
    op.drop_table('vacante')
    op.drop_index(op.f('ix_persona_email'), table_name='persona')
    op.drop_table('persona')
    # ### end Alembic commands ###
